"""init

Revision ID: 43e2810e4048
Revises: 
Create Date: 2023-12-07 21:32:55.916578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e2810e4048'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema bchain")
    op.create_table('t_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bchain',
    comment='Users'
    )
    op.create_index(op.f('ix_bchain_t_block_body'), 't_block', ['body'], unique=False, schema='bchain')
    op.create_index(op.f('ix_bchain_t_block_hash'), 't_block', ['hash'], unique=False, schema='bchain')
    op.create_index(op.f('ix_bchain_t_block_id'), 't_block', ['id'], unique=False, schema='bchain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bchain_t_block_id'), table_name='t_block', schema='bchain')
    op.drop_index(op.f('ix_bchain_t_block_hash'), table_name='t_block', schema='bchain')
    op.drop_index(op.f('ix_bchain_t_block_body'), table_name='t_block', schema='bchain')
    op.drop_table('t_block', schema='bchain')
    op.execute("drop schema bchain")
    # ### end Alembic commands ###
